<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Ip.Server</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Ip.Shared/Ip.Shared.csproj" />
    <ProjectReference Include="../Ip.Client/Ip.Client.csproj" />
  </ItemGroup>

</Project>
