@startuml
left to right direction
skinparam packageStyle rectangle

actor 利用者
actor 通信ツール
rectangle コマンド生成 {
    usecase (基本コマンドリストファイルを作成する)
    usecase (基本コマンドリストの中から生成したいコマンドを選択する)
    package 選択したコマンドの編集 {
        usecase (選択したコマンドに名前をつける)
        usecase (選択したコマンドのパラメータを編集する)
        usecase (選択したコマンドのリストを出力する)
    }
    package 基本コマンドリスト編集 {
        usecase (基本コマンドリストファイル入力)
        usecase (基本コマンド追加)
        usecase (基本コマンド削除)
        usecase (基本コマンド形式設定)
        usecase (基本コマンドリストファイル出力)
    }

    利用者 -- (基本コマンドリストファイルを作成する)
    利用者 -- (基本コマンドリストの中から生成したいコマンドを選択する)
    
    基本コマンドリスト編集 .-> (基本コマンドリストファイルを作成する):include
    選択したコマンドの編集 .-> (基本コマンドリストの中から生成したいコマンドを選択する):include

    選択したコマンドのリストを出力する -- 通信ツール
}
@enduml